# Generated by Django 4.2.16 on 2025-02-09 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=60)),
                ('caterer_description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_description', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('available_to', models.DateField(default=django.utils.timezone.now)),
                ('sample_image', models.ImageField(blank=True, default='menu_default.jpg', null=True, upload_to='menu_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('order_qualities', models.IntegerField()),
                ('unit_discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pick_up_at', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=60)),
                ('order_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
