# Generated by Django 4.2.16 on 2025-02-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='max_serve_qualities',
        ),
    ]
