# Generated by Django 4.2.16 on 2025-02-09 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='caterer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='orders.caterer'),
        ),
        migrations.AddField(
            model_name='menu',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caterer',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterer', to=settings.AUTH_USER_MODEL),
        ),
    ]
