# Generated by Django 4.2.16 on 2025-01-26 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='menu',
            name='available_to',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
