# Generated by Django 4.2.16 on 2025-02-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caterer',
            name='caterer_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
