# Generated by Django 4.2.16 on 2025-01-26 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menu_available_from_menu_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='available_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
