# Generated by Django 4.2.16 on 2025-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_menu_available_from_alter_menu_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_pics/'),
        ),
    ]
