# Generated by Django 4.2.16 on 2025-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_menu_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sample_image',
            field=models.ImageField(blank=True, default='menu_default.jpg', null=True, upload_to='menu_pics'),
        ),
    ]
